#version: '3.8'
#
#services:
#  postgres:
#    image: postgres:15-alpine
#    container_name: shift_management_db
#    environment:
#      POSTGRES_DB: shift_management
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - shift_network
#
#  backend:
#    build: ./backend
#    container_name: shift_management_backend
#    environment:
#      DB_HOST: postgres
#      DB_PORT: 5432
#      DB_USERNAME: jpgua
#      DB_PASSWORD: 12345678
#      DB_NAME: shift_management
#      NODE_ENV: production
#    ports:
#      - "3001:3001"
#    depends_on:
#      - postgres
#    networks:
#      - shift_network
#
#volumes:
#  postgres_data:
#
#networks:
#  shift_network:
#    driver: bridge
